# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install proj-bin
        sudo apt install openjdk-8-jre
        python -m pip install --upgrade pip
        python -m pip install poetry
        poetry install
        # Only Test GeoPandas and Pyspark API for supported Python versions:
        if [ "${{ matrix.python-version }}" -lt "3.11" ]; then echo "Install Pyspark" && poetry add pyspark; fi
        if [ "${{ matrix.python-version }}" -eq "3.8" ]; then echo "Install GeoPandas" && poetry add geopandas; fi
    - name: Test with pytest
      run: |
        poetry run pytest --color=yes -s -x -vv --cov-report term-missing --cov=pandas_bokeh Tests/
